Add new options for IPFS Cluster
dappforce/dappforce-subsocial-starter pull request #30
Opened 2020-09-24 17:10 UTC by F3Joule

2020-10-07 16:30 UTC, F3Joule commented on compose-files/ipfs.yml
>          ipv4_address: $IPFS_CLUSTER_IP
```suggestion
        ipv4_address: $IPFS_CLUSTER_IP

```

2020-10-07 16:30 UTC, F3Joule commented on start.sh
> +                printf $COLOR_R'WARN: jq is not installed on your system. Trying to install, root permissions may be required...\n'$COLOR_RESET >&2
```suggestion
                printf $COLOR_R'WARN: jq is not installed on your system.'$COLOR_RESET >&2
                printf 'Trying to install the jq, root permissions may be required...\n'
```

2020-10-21 13:57 UTC, siman requested changes

2020-10-21 13:57 UTC, siman commented on README.md
> +You can specify initial peers (bootnodes) to be able to connect to Subsocial as a cluster peer:
```suggestion
You can specify initial IPFS cluster bootnodes in order to connect to Subsocial as a cluster peer. Example:
```

2020-10-21 13:57 UTC, siman commented on README.md
> +- To add a peer:
```suggestion
**To add a peer:**
```

2020-10-21 13:57 UTC, siman commented on README.md
> +- To remove a peer:
```suggestion
**To remove a peer:**
```

2020-10-21 13:57 UTC, siman commented on README.md
> +- To entirely override trusted peers:
```suggestion
**To entirely override trusted peers:**
```

2020-10-21 13:57 UTC, siman commented on README.md
> +**Note:** that when you override, you should provide JSON like array of peers.
```suggestion
**NOTE:** that when you override, you should provide JSON like array of peers.
```

2020-10-21 13:57 UTC, siman commented on README.md
> +**Note:** all - add, remove and override should have every Peer URI wrapped by double quotes.
```suggestion
**NOTE:** all - add, remove and override should have every Peer URI wrapped by double quotes.
```

2020-10-21 13:57 UTC, siman commented on README.md
> +You can get *Peer URI* (e.g `/ip4/172.15.0.9/tcp/9096/p2p/12D3KooWD8YVcSx6ERnEDXZpXzJ9ctkTFDhDu8d1eQqdDsLgPz7V`) using `--cluster-id` option:
```suggestion
To get *Peer URI* (e.g `/ip4/172.15.0.9/tcp/9096/p2p/12D3KooWD8YVcSx6ERnEDXZpXzJ9ctkTFDhDu8d1eQqdDsLgPz7V`) use `--cluster-id` option:
```

2020-10-21 13:57 UTC, siman commented on README.md
> +| `--cluster-peers <add/remove/override>`| This will add remove or override trusted peers in IPFS Cluster. Example: `./start.sh --cluster-peers add '["*"]'` |
```suggestion
| `--cluster-peers <add/remove/override>`| Add, remove or override trusted peers to/from IPFS Cluster. Example: `./start.sh --cluster-peers add '["*"]'` |
```

2020-10-21 13:57 UTC, siman commented on README.md
> +| `--cluster-id`                     | Shows IPFS Cluster peers if it's running. |
```suggestion
| `--cluster-id`                     | Show IPFS Cluster peers if it's running. |
```

2020-10-21 13:57 UTC, siman commented on README.md
> +| `--cluster-secret`                 | Specify IPFS Cluster secret if consensus is RAFT. This one should be equal for all cluster nodes. |
```suggestion
| `--cluster-secret`                 | Specify IPFS Cluster secret if consensus is RAFT. Cluster secret must be equal across all cluster nodes. |
```

2020-10-21 13:57 UTC, siman commented on README.md
> +| `--cluster-peername`               | Specify IPFS Cluster peer name. This one should be unique for all cluster nodes. |
```suggestion
| `--cluster-peername`               | Specify IPFS Cluster peer name. Each Cluster node must have its own unique peer name. |
```

2020-10-21 13:57 UTC, siman commented on compose-files/ipfs.yml
> +      CLUSTER_CRDT_TRUSTEDPEERS: '' # Initially nobody is trusted
```suggestion
      CLUSTER_CRDT_TRUSTEDPEERS: '' # Trust none by default
```

2020-10-21 13:58 UTC, merged